### ISSUE TITLE
Use `go-jose.v1` instead of `go-jose`

### ISSUE THREAD

**Issue by willdurand** [auth0-community/go-auth0#6]
Hi!

It looks like the `go-jose` library has a version 2. Installing `go-auth0` does not work anymore (for me at least). I think it is because when importing `go-jose`, [dep](https://github.com/golang/dep) picks the `v2` instead of the `v1`. Could it be possible to explicit the use of `v1`?

Thanks!

---
Stack trace:

```
api_1  | # github.com/TailorDev/crick/api/vendor/github.com/auth0-community/go-auth0
api_1  | vendor/github.com/auth0-community/go-auth0/jwk_client.go:26: undefined: "github.com/TailorDev/crick/api/vendor/github.com/square/go-jose".JsonWebKey
```

**Comment by willdurand** [comment]
As a temporary solution (and to prove that the issue is valid), I have added the following content to my `Gopkg.toml`:

```
[[overrides]]
name = "github.com/square/go-jose"
version = "^1.1.0"
```

(Yet, `overrides` should not be used with `dep`)

**Comment by yageek** [comment]
The `v2` is using on purpose. Using the `v2` is an issue for you? Can you provide more information?

**Comment by scottcrespo** [comment]
Hi,

I'm running into similar problems. I'm using [glide](https://github.com/Masterminds/glide) for package management. 

I tried to install the `go-jose` dependency at different versions and from different sources (github.com and gopkg.in) with no luck at compiling. Here's a recap of what I tried to do:

```
Installed "gopkg.in/square/go-jose.v2"

# github.com/scottcrespo/cloee_api/vendor/github.com/auth0-community/go-auth0
../vendor/github.com/auth0-community/go-auth0/jwk_client.go:26: undefined: "github.com/scottcrespo/cloee_api/vendor/github.com/square/go-jose".JsonWebKey

Installed "gopkg.in/square/go-jose.v1"

# github.com/scottcrespo/cloee_api/vendor/github.com/auth0-community/go-auth0
../vendor/github.com/auth0-community/go-auth0/jwk_client.go:26: undefined: "github.com/scottcrespo/cloee_api/vendor/github.com/square/go-jose".JsonWebKey

Installed "github.com/square/go-jose"

# github.com/scottcrespo/cloee_api/vendor/github.com/auth0-community/go-auth0
../vendor/github.com/auth0-community/go-auth0/jwk_client.go:26: undefined: "github.com/scottcrespo/cloee_api/vendor/github.com/square/go-jose".JsonWebKey


Installed "github.com/square/go-jose" @ aa2e30fdd1fe9dd3394119af66451ae790d50e0d (version 1.1) and "gopkg.in/square/go-jose.v1"

# github.com/scottcrespo/cloee_api/vendor/github.com/auth0-community/go-auth0
../vendor/github.com/auth0-community/go-auth0/jwk_client.go:26: undefined: "github.com/scottcrespo/cloee_api/vendor/github.com/square/go-jose".JsonWebKey
```

Looking at [jwk_client.go](https://github.com/auth0-community/go-auth0/blob/master/jwk_client.go#L10) i see the import path is `github.com/square/go-jose`, but elsewhere in the project the import path uses `gopkg.in/square/go-jose.v2` [see here](https://github.com/auth0-community/go-auth0/blob/master/auth0.go#L7)

Thus, with the current state of this project, it's probably necessary to install go-jose from both `github.com` and `gopkg.in` at specific versions (which versions, I'm not yet sure). 


### Initial Thoughts

I think the discrepancy between import statements might be causing problems with compilation, since I'm not sure what is the required versions and sources of go-jose. Using a single installation of the latest `go-jose` from `gopkg.in` (for version support) might help alleviate the problem.

If the discrepancy is necessary, do you know specifically what sources and versions of `go-jose` need to be installed?

Hope this information is useful! Please let me know if there's anything else you need from me.

**Comment by yageek** [comment]
I did not noticed 😞 The visual studio code importer is not always a good idea. I will work on a PR to fix it soon.

**Comment by scottcrespo** [comment]
@yageek 

Indeed, from time-to-time, I have the same problem with my Atom editor and auto-import.

**Comment by willdurand** [comment]
Heya, sorry to get back to you only now. Thanks for having fixed this bug, and @scottcrespo thanks for all the information you provided!
